base = (
  # HTTP responses
  ("../301.html", "https://malekaia.co.uk/404.html"),
  ("../404.html", "https://malekaia.co.uk/404.html"),
  ("../410.html", "https://malekaia.co.uk/404.html"),
  # Root directories
  ("../about.html", "https://malekaia.co.uk/about/"),
  ("../about/index.html", "https://malekaia.co.uk/about/"),
  ("../articles.html", "https://malekaia.co.uk/articles/"),
  ("../articles/index.html", "https://malekaia.co.uk/articles/"),
  ("../contact.html", "https://malekaia.co.uk/about/#contact"),
  ("../contact/index.html", "https://malekaia.co.uk/about/#contact"),
  ("../img.html", "https://malekaia.co.uk/404.html"),
  ("../img/index.html", "https://malekaia.co.uk/404.html"),
  ("../index.html", "https://malekaia.co.uk/"),
  ("../info.html", "https://malekaia.co.uk/about/#overview"),
  ("../info/index.html", "https://malekaia.co.uk/about/#overview")
)

articles = (
  ("../articles/Bootstrap/how_to_change_the_default_font_in_bootstrap.html", "https://malekaia.co.uk/articles/CSS/how_to_change_the_default_font_in_bootstrap.html"),
  ("../articles/CSS/how_to_change_the_default_font_in_bootstrap.html", "https://malekaia.co.uk/articles/CSS/how_to_change_the_default_font_in_bootstrap.html"),
  ("../articles/CSS/how_to_extend_parent_selectors_in_sass.html", "https://malekaia.co.uk/articles/Sass/how_to_extend_parent_selectors_in_sass.html"),
  ("../articles/Git/how_to_avoid_overusing_the_git_keyword.html", "https://malekaia.co.uk/portfolio/NoGit/"),
  ("../articles/Git/how_to_avoid_retyping_the_git_keyword.html", "https://malekaia.co.uk/portfolio/NoGit/"),
  ("../articles/Go/globbing_in_go.html", "https://malekaia.co.uk/articles/Go/globbing_in_go.html"),
  ("../articles/Go_Lang/globbing_in_go.html", "https://malekaia.co.uk/articles/Go/globbing_in_go.html"),
  ("../articles/HTML/how_to_open_html_links_in_new_tabs.html", "https://malekaia.co.uk/articles/HTML/how_to_open_html_links_in_new_tabs.html"),
  ("../articles/HTML/how_to_open_html_links_in_new_tabs.html", "https://malekaia.co.uk/articles/HTML/how_to_open_html_links_in_new_tabs.html"),
  ("../articles/JavaScript/environment_detection_in_javascript.html", "https://malekaia.co.uk/articles/JavaScript/environment_detection_in_javascript.html"),
  ("../articles/JavaScript/how_to_check_if_a_javascript_function_is_empty.html", "https://malekaia.co.uk/articles/JavaScript/how_to_check_if_a_javascript_function_is_empty.html"),
  ("../articles/JavaScript/how_to_modify_regexp_flags.html", "https://malekaia.co.uk/articles/JavaScript/how_to_modify_regexp_flags.html"),
  ("../articles/JavaScript/how_to_select_sibling_elements_using_javascript.html", "https://malekaia.co.uk/articles/JavaScript/how_to_select_sibling_elements_using_javascript.html"),
  ("../articles/JavaScript/rudimentary_performance_testing_in_javascript.html", "https://malekaia.co.uk/articles/JavaScript/rudimentary_performance_testing_in_javascript.html"),
  ("../articles/jQuery/how_to_modify_the_jquery_global_without_modifying_jquery.html", "https://malekaia.co.uk/404.html"),
  ("../articles/jQuery/how_to_scroll_to_an_element_on_click.html", "https://malekaia.co.uk/404.html"),
  ("../articles/Node.js/brace_expansion_in_shelljs.html", "https://malekaia.co.uk/404.html"),
  ("../articles/Node.js/environment_detection_in_javascript.html", "https://malekaia.co.uk/articles/JavaScript/environment_detection_in_javascript.html"),
  ("../articles/Perl/how_to_call_a_subprocess_in_perl.html", "https://malekaia.co.uk/articles/Perl/how_to_call_a_subprocess_in_perl.html"),
  ("../articles/Perl/how_to_unzip_an_archive_using_perl.html", "https://malekaia.co.uk/articles/Perl/how_to_call_a_subprocess_in_perl.html"),
  ("../articles/Pip/an_introduction_to_the_pip_package_manager.html", "https://malekaia.co.uk/articles/Python/an_introduction_to_the_pip_package_manager.html"),
  ("../articles/Python/a_guide_to_pythons_data_types.html", "https://malekaia.co.uk/articles/Python/a_guide_to_pythons_data_types.html"),
  ("../articles/Python/an_introduction_to_the_pip_package_manager.html", "https://malekaia.co.uk/articles/Python/an_introduction_to_the_pip_package_manager.html"),
  ("../articles/Python/how_to_create_a_development_server_using_http_server.html", "https://malekaia.co.uk/articles/Python/how_to_create_a_development_server_using_http_server.html"),
  ("../articles/Rust/a_brief_introduction_to_memory_management_in_rust.html", "https://malekaia.co.uk/articles/Rust/a_brief_introduction_to_memory_management_in_rust.html"),
  ("../articles/Rust/a_rustaceans_introduction_to_the_cargo_package_manager.html", "https://malekaia.co.uk/articles/Rust/a_rustaceans_introduction_to_the_cargo_package_manager.html"),
  ("../articles/Rust/how_to_install_rust_on_unix.html", "https://malekaia.co.uk/articles/Rust/how_to_install_rust_on_unix.html"),
  ("../articles/Rust/why_type_declarations_for_rust_constants_should_be_unnecessary.html", "https://malekaia.co.uk/articles/Rust/why_type_declarations_for_rust_constants_should_be_unnecessary.html"),
  ("../articles/SASS/how_to_extend_parent_selectors_in_sass.html", "https://malekaia.co.uk/articles/Sass/how_to_extend_parent_selectors_in_sass.html"),
  ("../articles/Web_Development/a_non_technical_introduction_to_http_and_https.html", "https://malekaia.co.uk/articles/Networking/a_nontechnical_introduction_to_http_and_https.html"),
  ("../articles/Web_Development/how_to_create_a_development_server_using_http_server.html", "https://malekaia.co.uk/articles/Python/how_to_create_a_development_server_using_http_server.html"),
  ("../articles/Web_Development/how_to_setup_a_development_server_using_express.html", "https://malekaia.co.uk/404.html"),
  ("../articles/Web_Development/how_to_setup_a_development_server_using_flask.html", "https://malekaia.co.uk/404.html")
)
